repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: 'v1.5.0'  # Correctly formatted tag with 'v' prefix
    hooks:
      - id: detect-secrets
        args: ['--no-verify']
        exclude: '^.secrets.baseline$'
