version: v1
name: postgres
type: depot
layer: user
description: "The purpose of postgres depot to consume data to create consumer Aligned Data Product"
depot:
  type: JDBC
  description: "The purpose of postgres depot to consume data to create consumer Aligned Data Product"
  external: true
  source: postgres
  connectionSecret:
    - acl: rw
      type: key-value-properties
      data:
        username: postgres
        password: 12345
  spec:
    host: sandbox.postgres.database.azure.com
    port: 5432
    database: postgres
    subprotocol: "postgresql"